<div class="container">
    <div class="col-md-12 text-center">
        <h1><?php echo $this->translate( 'xrace-admin' ); ?></h1>
    </div>
    <div class="row">
        <div class="container menu">
			<div class="col-sm-6 col-md-3">
				<div class="thumbnail tile tile-medium text-center">
					<a href="/user" >
						<h2>
							<i class="fa fa-users"></i>
							 <span>USER</span> 
						</h2>
					</a>
				</div>
			</div>
			<div class="col-sm-6 col-md-3">
				<div class="thumbnail tile tile-medium text-center">
					<a href="/product-group" >
						<h2>
							<i class="fa fa-gift"></i>
							<span class="tow-row">PRODUCT GROUP</span> 
						</h2>
					</a>
				</div>
			</div>
			<div class="col-sm-6 col-md-3">
				<div class="thumbnail tile tile-medium text-center">
					<a href="/product" >
						<h2>
							<i class="fa fa-life-ring"></i>
							<span>PRODUCT</span> 
						</h2>
					</a>
				</div>
			</div>
			<div class="col-sm-6 col-md-3">
				<div class="thumbnail tile tile-medium text-center">
					<a href="#" >
						<h2>
							<i class="fa fa-cog"></i>
							<span>CONFIG GAME</span> 
						</h2>
					</a>
				</div>
			</div>
			
        </div>
    </div>
</div>