<div id="select-home" class="container wrapperIndex">
	<div class="col-md-12 text-center title">
		<h1>XRace Management System</h1>
	</div>
    <div class="form-group col-md-12 padding-left padding-right text-center">
		<a href="/user"> 
			<div class="col-md-2 widgetIndex widget-shadow">
				<p><i class="fa fa-user"></i> <span>USER LOCAL</span></p>
			</div>
		</a>
		<a href="/product-group"> 
			<div class="col-md-2 widgetIndex widget-shadow">
				<p><i class="fa fa-cubes"></i> <span>PRODUCT GROUP</span></p>
			</div>
		</a>
		<a href="/product"> 
			<div class="col-md-2 widgetIndex widget-shadow">
				<p><i class="fa fa-life-ring"></i> <span>PRODUCT</span></p>
			</div>
		</a>
		<a href="/order-detail"> 
			<div class="col-md-2 widgetIndex widget-shadow last">
				<p><i class="fa fa-credit-card"></i> <span>ORDER</span></p>
			</div>
		</a>
	</div>
	<div class="form-group col-md-12 padding-left padding-right text-center">
		<a href="/member"> 
			<div class="col-md-2 widgetIndex widget-shadow">
				<p><i class="fa fa-user"></i> <span>USER</span></p>
			</div>
		</a>
		<a href="/group-user"> 
			<div class="col-md-2 widgetIndex widget-shadow">
				<p><i class="fa fa-users"></i> <span>GROUP USER</span></p>
			</div>
		</a>
		<a href="/group-join"> 
			<div class="col-md-2 widgetIndex widget-shadow">
				<p><i class="fa fa-cog"></i> <span>GROUP JOIN</span></p>
			</div>
		</a>
		<a href="/group-invite"> 
			<div class="col-md-2 widgetIndex widget-shadow last">
				<p><i class="fa fa-credit-card"></i> <span>GROUP INVITE</span></p>
			</div>
		</a>
</div>
