<div class="container-fluid">
	<div class="row">
	    <div class="col-md-12">
			<form class="form-inline x-form" enctype="multipart/form-data" role="form" method="POST" name="memberDetailForm">
	      	<div>
				<h3>User</h3>
				<hr/>
			</div>
			<div class="widget blue">
	      		<div class="widget-title">
				    <h4><i class="fa fa-navicon"></i> DETAIL</h4>
				</div>
	      		<div class="widget-body search-form">
	      			<div class="container-left">
	      <?php echo $this->partial( "/partials/_errors.phtml", array( "errors" => $this->error ) ); ?>
	        <fieldset>
	    	<div class="form-group col-md-12">
	    		<div class="col-md-2 padding-left">
	    			<label>User Name</label>
	    			<input disabled="disabled" type="text" placeholder="<?php echo $this->translate('user-name')?>" class="form-control" name="id" value="<?php echo @$this->info['user_name']?>">
	    		</div>
	    		<div class="col-md-2">
	    			<label>Email</label>
	    			<input disabled="disabled" type="text" placeholder="<?php echo $this->translate('email')?>" class="form-control" name="email" value="<?php echo @$this->info['email']?>">
	    		</div>
	    		<div class="col-md-2">
	    			<label><?php echo $this->translate('status')?></label>
	    			<input type="text" disabled="disabled" placeholder="<?php echo $this->translate('status')?>" class="form-control" name="amount" value="<?php echo @$this->info['status']?>">
	    		</div>
	    		<div class="col-md-2">
	    			<label><?php echo $this->translate('gender')?></label>
	    			<input type="text" disabled="disabled" data-type="" placeholder="<?php echo $this->translate('gender')?>" class="form-control" name="gender" value="<?php echo @$this->info['gender']?>">
	    		</div>
	    		<div class="col-md-2">
	    			<label>Birthday</label>
	    			<input type="text" disabled="disabled" data-type="price" placeholder="<?php echo $this->translate('birthday')?>" class="form-control" name="birthday" value="<?php echo @$this->info['birthday']?>">
	    		</div>
				<div class="col-md-2 padding-right">
	    			<label>Created At</label>
	    			<input type="text" disabled="disabled" placeholder="<?php echo $this->translate('created-at')?>" class="form-control" name="createAt" value="<?php echo @$this->info['created_at']?>">
	    		</div>
	        </div>
	        <div class="form-group col-md-12">
	            <div class="pull-right">
	                <button type="button" class="btn btn-default" onclick="window.location = '<?php echo '/'.$this->controller?>';">CANCEL</button>
	            </div>
	        </div>
	        </fieldset>
			</div>
			</div>
			</div>
	      </form>
	    </div><!-- /.col-lg-12 -->
	</div><!-- /.row -->
</div>