<div class="container-fluid">
    <div class="row" style="padding-bottom: 20px">
        <div class="col-md-12">
            <div>
                <h3>User List</h3>
            </div>
            <hr/>
            <form class="form-inline search-form search-form-datatable" role="form" method="get" 
            		onsubmit="return false;" action="" id="searchOrderForm">
            		<div class="container-left ">
            			<div class="col-md-12 padding-left padding-right">
            				<div class="form-group col-md-3">
                				<label for="">User Name</label>
                				<input id="userName" type="text" class="form-control searchItem" placeholder="<?php echo $this->translate( 'user-name' ); ?>"
                           			mapping-column="1" item-type="search" data-type="" data-format=""/>
                			</div>
                			<div class="form-group col-md-3">
                				<label for="">Email</label>
                				<input id="email" type="text" class="form-control searchItem" placeholder="<?php echo $this->translate( 'email' ); ?>"
                           			mapping-column="2" item-type="search" data-type="" data-format=""/>
                			</div>
                			<div class="form-group col-md-3">
                				<label for="">Gender</label>
                				<select id="currency" class="form-control no-search searchItem" 
			                            mapping-column="3" item-type="search" data-format="">
			                        	<option value=""><?php echo $this->translate( "all" ); ?></option>
			                        	<?php
			                        		foreach (Commons::getGender() as $key => $value ){ ?>
			                        		<option value="<?php echo $key?>"><?php echo $value;?></option>
			                        		<?php }?>
			                    </select>
                			</div>
                			<div class="form-group col-md-3">
                				<label for="">Created Date</label>
                				<input id="createDate" type="text" class="form-control searchItem datepicker"
                           			mapping-column="6" item-type="search" data-type="" data-format="dd-mm-yyyy" format='yyyy-mm-dd'/>
                			</div>
            			</div>
            			<div class="form-group col-md-12">
				            <p class="btn-search ">
				                <button type="button" class="btn btn-primary" id="btnSearch" onclick="PaymentAdmin.site.pages.Common.executeSearchForm('searchOrderForm', 'memberTable');">
				                    <i class="fa fa-search"></i> <?php echo $this->translate( 'search' ); ?>
				                </button>
				            </p>
				        </div>
            		</div>
            		
            </form>
    	</div>
    </div>
    <div class="row">
	    <div class="col-md-12">
	    	<table id="memberTable" class="data-table display disable-state-save" cellspacing="0" width="">
	    		<thead>
	    			<tr>
	    				<th width="5%">ID</th>
	    				<th width="10%">User Name</th>
	    				<th>Email</th>
	    				<th width="5%">Gender</th>
	    				<th width="10%">Birthday</th>
	    				<th width="5%">Status</th>
	    				<th width="10%">Create at</th>
	    				<th width="35px">Action</th>
	    			</tr>
	    		</thead>
	    	</table>
	    </div>
    </div>
</div>
