<div class="container-fluid">
	<div class="row">
		<div class="col-md-12 form-group">
			<strong>GROUP USER DETAIL</strong>
		</div>
	</div>
	<div class="row">
	    <div class="col-md-12">
	      <form class="form-horizontal"  role="form" method="POST" name="memberDetailForm">
	      <?php echo $this->partial( "/partials/_errors.phtml", array( "errors" => $this->error ) ); ?>
	        <fieldset>
	    	<div class="form-group col-md-12">
	    		<div class="col-md-3 padding-left">
	    			<label><?php echo $this->translate('group-name')?></label>
	    			<input disabled="disabled" type="text" placeholder="<?php echo $this->translate('group-name')?>" class="form-control" name="id" value="<?php echo @$this->info['group_name']?>">
	    		</div>
	    		<div class="col-md-3">
	    			<label><?php echo $this->translate('user-create')?></label>
	    			<input disabled="disabled" type="text" placeholder="<?php echo $this->translate('user-create')?>" class="form-control" name="email" value="<?php echo @$this->info['user_create']?>">
	    		</div>
	    		<div class="col-md-3">
	    			<label><?php echo $this->translate('user-leader')?></label>
	    			<input type="text" disabled="disabled" placeholder="<?php echo $this->translate('user-leader')?>" class="form-control" name="productGroupName" value="<?php echo @$this->info['user_name_leader']?>">
	    		</div>
	    		<div class="col-md-3 padding-right">
	    			<label><?php echo $this->translate('status')?></label>
	    			<input type="text" disabled="disabled" placeholder="<?php echo $this->translate('status')?>" class="form-control" name="amount" value="<?php echo @$this->info['status']?>">
	    		</div>
	        </div>
	        <div class="form-group col-md-12">
				<div class="col-md-3 padding-left">
	    			<label><?php echo $this->translate('created-at')?></label>
	    			<input type="text" disabled="disabled" placeholder="<?php echo $this->translate('created-at')?>" class="form-control" name="createAt" value="<?php echo @$this->info['created_at']?>">
	    		</div>
	    		<div class="col-md-3">
	    			<label><?php echo $this->translate('group-slogan')?></label>
	    			<input type="text" disabled="disabled" data-type="" placeholder="<?php echo $this->translate('group-slogan')?>" class="form-control" name="gender" value="<?php echo @$this->info['group-slogan']?>">
	    		</div>
	    		<div class="col-md-3">
	    			<label><?php echo $this->translate('email-leader')?></label>
	    			<input type="text" disabled="disabled" data-type="price" placeholder="<?php echo $this->translate('email-leader')?>" class="form-control" name="birthday" value="<?php echo @$this->info['email_leader']?>">
	    		</div>
	    		<div class="col-md-3 padding-right">
	    			<label><?php echo $this->translate('phone')?></label>
	    			<input type="text" disabled="disabled" data-type="" placeholder="<?php echo $this->translate('phone')?>" class="form-control" name="phone" value="<?php echo @$this->info['phone']?>">
	    		</div>
	        </div>
	        <div class="form-group col-md-12">
	    		<div class="col-md-3 padding-left">
	    			<label><?php echo $this->translate('logo-url')?></label>
	    			<input type="text" disabled="disabled" data-type="" placeholder="<?php echo $this->translate('logo-url')?>" class="form-control" name="paymentTypeValue" value="<?php echo @$this->info['logo_url']?>">
	    		</div>
	        </div>
	        <div class="form-group col-md-12">
	            <div class="pull-right">
	                <button type="button" class="btn btn-default" onclick="window.location = '<?php echo '/'.$this->controller?>';">CANCEL</button>
	            </div>
	        </div>
	        </fieldset>
	      </form>
	    </div><!-- /.col-lg-12 -->
	</div><!-- /.row -->
</div>