<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div>
                <h3>Product Group List</h3>
            </div>
            <hr/>
        </div>
    </div>
    <div class="row">
    	<div class="col-md-12 text-left position">
			<button type="button" class="btn btn-success" onclick="window.location='/<?php echo $this->controller;?>/detail';"><i class="fa fa-crosshairs"></i> CREATE PRODUCT GROUP</button>
	    </div>
	    <div class="col-md-12">
	    	<table id="productGroupTable" class="data-table display" cellspacing="0" width="">
	    		<thead>
	    			<tr>
	    				<th>ID</th>
	    				<th>Product Name</th>
	    				<th>Product Rating</th>
	    				<th>Status</th>
	    				<th>City</th>
	    				<th>Duration</th>
	    				<th>Difficulty</th>
	    				<th>Local Knowledge</th>
	    				<th>Created At</th>
	    				<th>Member Min</th>
	    				<th>Member Max</th>
	    				<th>Gold</th>
	    				<th>Rule Id</th>
	    				<th width="35px">Action</th>
	    			</tr>
	    		</thead>
	    	</table>
	    </div>
    </div>
</div>
