
<div class="container-fluid">
	<div class="row">
	    <div class="col-md-12">
			<form class="form-inline x-form" enctype="multipart/form-data" role="form" method="POST" name="memberDetailForm">
	      	<div>
				<h3>Stage</h3>
				<hr/>
			</div>
			<div class="widget blue">
	      		<div class="widget-title">
				    <h4><i class="fa fa-navicon"></i> DETAIL</h4>
				</div>
	      		<div class="widget-body search-form">
	      			<div class="container-left">
			  <?php echo $this->partial( "/partials/_errors.phtml", array( "errors" => $this->error ) ); ?>
				<fieldset>
				<div class="form-group col-md-12 padding-left padding-right">
					<div class="col-md-4 padding-left">
						<label>Name</label>
						<input type="text"  placeholder="Name" class="form-control" id="name" name="name" value="<?php echo @$this->info['name']?>">
					</div>
					<div class="col-md-4">
						<label>Time Start</label>
						<input type="text" format="yyyy-mm-dd hh:ii:ss" placeholder="Time Start" class="form-control datetime-picker" id="end_time" name="time_start" value="<?php echo @$this->info['time_start']?>">
					</div>
					<div class="col-md-4">
						<label>End Time</label>
						<input type="text" format="yyyy-mm-dd hh:ii:ss" placeholder="End Time" class="form-control datetime-picker" id="end_time" name="end_time" value="<?php echo @$this->info['end_time']?>">
					</div>
				</div>
				<div class="form-group col-md-12 padding-left padding-right">
					<div class="col-md-6 padding-left">
						<label>Stage</label>
						<select multiple id="stage" name="list_stage[]" class="form-control">
					       <?php echo $this->partial( "/partials/_stage.phtml", array( "list" => $this->stageList, "value"=> explode(',', @$this->info['list_stage'] ), "isMulti" => true ) ); ?>
					    </select>
					    <input type="hidden" id="stage-hidden" value="<?php echo @$this->info['list_stage']?>"> 
						<script type="text/javascript">
							$("#stage").select2();
							var selectedValues = $("#stage-hidden").val().split(',');
							$("#stage").select2('val',selectedValues);
						</script>
					</div>
					<div class="col-md-6">
						<label>Description</label>
						<textarea type="text" rows='1' placeholder="Description" class="form-control" id="description" name="description"><?php echo @$this->info['description']?></textarea>
					</div>
				</div>
				<div class="form-group col-md-12 padding-right">
					<div class="pull-right">
						<button type="button" class="btn btn-default" onclick="window.location = '<?php echo '/'.$this->controller?>';">CANCEL</button>
						<button type="submit" id="submit" class="btn btn-primary">SUBMIT</button>
					</div>
				</div>
				</fieldset>
						</div>
					</div>
				</div>
			</form>
	    </div><!-- /.col-lg-12 -->
	</div><!-- /.row -->
</div>