<div class="container-fluid">
	<div class="row">
	    <div class="col-md-12">
			<form class="form-inline x-form"  role="form" method="POST" name="memberDetailForm" style="width: 50%;">
	      	<div class="widget blue">
	      		<div class="widget-title">
				    <h4><i class="fa fa-navicon"></i> CHANGE PASSWORD</h4>
				</div>
	      		<div class="widget-body search-form">
	      			<div class="container-left">
            <?php echo $this->partial( "/partials/_errors.phtml", array( "errors" => $this->error ) ); ?>
            <div class='form-group col-md-12 padding-left padding-right'>
                <label>Current password</label>
                <input name="OldPassword" id="OldPassword" class='form-control' type='password' value="<?php echo @$this->postData['OldPassword'] ?>">
            </div>
            <div class='form-group col-md-12 padding-left padding-right'>
                <label>New password</label>
                <input name="Password" id="Password" class='form-control' type='password' value="<?php echo @$this->postData['Password'] ?>">
            </div>
             <div class='form-group col-md-12 padding-left padding-right'>
                <label>Repeate password</label>
                <input name="RenewPassword" id="RenewPassword" class='form-control' type='password' value="<?php echo @$this->postData['RenewPassword'] ?>">
            </div>    
            <div class='form-group col-md-12 padding-left padding-right'>
                <button class='form-control btn btn-primary submit-button' type='submit'>Change password</button>                
            </div>
			</div>
			</div>
			</div>
          </form>
        </div>
    </div>
</div>
