<div class="container">
    <div class='row'>
        <div class='widget-body col-sm-4 col-md-offset-4'>
          <form accept-charset="UTF-8" action="" method="post" class="form require-validation">
            <?php echo $this->partial( "/partials/_errors.phtml", array( "errors" => $this->error ) ); ?>
            <div class='form-row'>
              <div class='col-xs-12 form-group required'>
                <label class='control-label'>Current password</label>
                <input name="OldPassword" id="OldPassword" class='form-control' type='password' value="<?php echo @$this->postData['OldPassword'] ?>">
              </div>
            </div>
            <div class='form-row'>
              <div class='col-xs-12 form-group card required'>
                <label class='control-label'>New password</label>
                <input name="Password" id="Password" class='form-control' type='password' value="<?php echo @$this->postData['Password'] ?>">
              </div>
            </div>
             <div class='form-row'>
              <div class='col-xs-12 form-group card required'>
                <label class='control-label'>Repeate password</label>
                <input name="RenewPassword" id="RenewPassword" class='form-control' type='password' value="<?php echo @$this->postData['RenewPassword'] ?>">
              </div>
            </div>    
           
            <div class='form-row'>
              <div class='col-md-12 form-group'>
                <button class='form-control btn btn-primary submit-button' type='submit'>Change password</button>                
              </div>
            </div>
          </form>
        </div>
    </div>
</div>
</div>
<br>
<div class="panel panel-danger"></div>