<div class="container-fluid">
	<div class="row">
	    <div class="col-md-12">
			<form class="form-inline x-form" enctype="multipart/form-data" role="form" method="POST" name="memberDetailForm">
	      	<div>
				<h3>Account</h3>
				<hr/>
			</div>
			<div class="widget blue">
	      		<div class="widget-title">
				    <h4><i class="fa fa-navicon"></i> DETAIL</h4>
				</div>
	      		<div class="widget-body search-form">
	      			<div class="container-left">
	      <?php echo $this->partial( "/partials/_errors.phtml", array( "errors" => $this->error ) ); ?>
	        <fieldset>
	    	<div class="form-group col-md-8 padding-left padding-right">
	    		<div class="col-md-6">
	    			<label>User Name</label>
	    			<input type="text" <?php if ( intval( $this->id) > 0 ) {
	    				echo "disabled";
	    			}?> placeholder="User Name" class="form-control" name="user_name" value="<?php echo @$this->info['user_name']?>">
	    		</div>
	    		
	        </div>
	        <div class="form-group col-md-8 padding-left padding-right <?php if(intval( @$this->id ) > 0){ echo 'hidden'; } ?>">
	        	<div class="col-md-6">
	    			<label>Password</label>
	    			<input type="password" placeholder="Password" class="form-control" name="password" value="<?php echo @$this->info['password']?>">
	    		</div>
	    		<div class="col-md-6">
	    			<label>Retype Password</label>
	    			<input type="password" placeholder="Password" class="form-control" name="retype-password" value="<?php echo @$this->info['password']?>">
	    		</div>
	        </div>
	        <div class="form-group col-md-8 padding-left padding-right">
	    		<div class="col-md-6">
	    			<label>Email</label>
	    			<input type="text" placeholder="Email" class="form-control" name="email" <?php if ( intval( $this->id) > 0 ) {
	    				echo "disabled";
	    			}?> value="<?php echo @$this->info['email']?>">
	    		</div>
	    		<div class="col-md-6">
	    			<label>Full Name</label>
	    			<input type="text" placeholder="Full name" class="form-control" name="full_name" value="<?php echo @$this->info['full_name']?>">
	    		</div>
	        </div>
	
	          <div class="form-group col-md-8">
	              <div class="pull-right">
	                <button type="button" class="btn btn-default" onclick="window.location = '<?php echo '/'.$this->controller?>';">CANCEL</button>
	                <button type="submit" class="btn btn-primary">SUBMIT</button>
	              </div>
	          </div>
	        </fieldset>
			</div>
			</div>
			</div>
	      </form>
	    </div><!-- /.col-lg-12 -->
	</div><!-- /.row -->
</div>