<div class="container-fluid">
	<div class="row">
	    <div class="col-md-12" style="align:center">
	      <form class="form-horizontal" role="form" method="POST">
	      <?php echo $this->partial( "/partials/_errors.phtml", array( "errors" => $this->error ) ); ?>
	        <fieldset>
	    	<div class="form-group col-md-8">
	    		<div class="col-md-6">
	    			<label>User Name</label>
	    			<input type="text" placeholder="User Name" class="form-control" name="user_name" value="<?php echo @$this->info['user_name']?>">
	    		</div>
	    		<div class="col-md-6">
	    			<label>Password</label>
	    			<input <?php if(intval( @$this->id ) > 0){ echo "disabled"; } ?> type="password" placeholder="Password" class="form-control" name="password" value="<?php echo @$this->info['password']?>">
	    		</div>
	        </div>
	        <div class="form-group col-md-8">
	    		<div class="col-md-6">
	    			<label>Email</label>
	    			<input type="text" placeholder="Email" class="form-control" name="email" value="<?php echo @$this->info['email']?>">
	    		</div>
	    		<div class="col-md-6">
	    			<label>Full Name</label>
	    			<input type="text" placeholder="Full name" class="form-control" name="full_name" value="<?php echo @$this->info['full_name']?>">
	    		</div>
	        </div>
	
	          <div class="form-group col-md-8">
	              <div class="pull-right">
	                <button type="button" class="btn btn-default" onclick="window.location = '<?php echo '/'.$this->controller?>';">CANCEL</button>
	                <button type="submit" class="btn btn-primary">SUBMIT</button>
	              </div>
	          </div>
	        </fieldset>
	      </form>
	    </div><!-- /.col-lg-12 -->
	</div><!-- /.row -->
</div>