<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div>
                <h3><?php echo $this->translate( "user" ); ?></h3>
            </div>
            <hr/>
        </div>
    </div>
    <div class="row">
	    <div class="col-md-12">
	    	<table id="userTable" class="data-table display" cellspacing="0" width="100%">
	    		<thead>
	    			<tr>
	    				<th>ID</th>
	    				<th>User Name</th>
	    				<th>Email</th>
	    				<th>Status</th>
	    				<th>Full Name</th>
	    				<th>Action</th>
	    			</tr>
	    		</thead>
	    	</table>
	    </div>
    </div>
</div>
