<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div>
                <h3>Account List</h3>
            </div>
            <hr/>
        </div>
    </div>
    <div class="row">
    	<div class="col-md-12 text-left position">
			<button type="button" class="btn btn-success" onclick="window.location='/<?php echo $this->controller;?>/detail';"><i class="fa fa-crosshairs"></i> CREATE USER</button>
	    </div>
	    <div class="col-md-12">
	    	<table id="userTable" class="data-table display" cellspacing="0" width="100%">
	    		<thead>
	    			<tr>
	    				<th>ID</th>
	    				<th>User Name</th>
	    				<th>Email</th>
	    				<th>Status</th>
	    				<th>Full Name</th>
	    				<th width="35px" >Action</th>
	    			</tr>
	    		</thead>
	    	</table>
	    </div>
    </div>
</div>
