
<div class="container-fluid">
	<div class="row">
	    <div class="col-md-12">
			<form class="form-inline x-form" enctype="multipart/form-data" role="form" method="POST" name="memberDetailForm">
	      	<div>
				<h3>Referral File</h3>
				<hr/>
			</div>
			<div class="widget blue">
	      		<div class="widget-title">
				    <h4><i class="fa fa-navicon"></i> DETAIL</h4>
				</div>
	      		<div class="widget-body search-form">
	      			<div class="container-left">
			  <?php echo $this->partial( "/partials/_errors.phtml", array( "errors" => $this->error ) ); ?>
				<fieldset>
				<div class="form-group col-md-12 padding-left padding-right">
					<div class="col-md-4 padding-left">
						<label>Name</label>
						<input type="file" class="form-control" id="fileName" name="fileName" value="<?php echo @$this->info['file_name']?>">
						<input type="hidden" name="file_name_hid" value="<?php echo @$this->info['file_name']?>">
					</div>
					<div class="col-md-4">
						<label>Code</label>
						<input type="text"  placeholder="Code" class="form-control" id="code" name="code" value="<?php echo @$this->info['code']?>">
					</div>
					<div class="col-md-2 padding-right">
						<label>Url Share File</label>
						<strong style="padding-top: 8px;display: inherit;"><?php echo 'http://'.$_SERVER['HTTP_HOST'].'/';?>download/index?&fileshare=</strong>
					</div>
					<div class="col-md-2 padding-right padding-left">
						<label>&nbsp;</label>
						<input type="text"  placeholder="" class="form-control" id="code" name="url_share_file" value="<?php echo @$this->info['url_share_file']?>">
					</div>
				</div>
				<div class="form-group col-md-12 padding-right">
					<div class="pull-right">
						<button type="button" class="btn btn-default" onclick="window.location = '<?php echo '/'.$this->controller?>';">CANCEL</button>
						<button type="submit" id="submit" class="btn btn-primary">SUBMIT</button>
					</div>
				</div>
				</fieldset>
						</div>
					</div>
				</div>
			</form>
	    </div><!-- /.col-lg-12 -->
	</div><!-- /.row -->
</div>