<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div>
                <h3>Referral And File List</h3>
            </div>
            <hr/>
        </div>
    </div>
    <div class="row">
    	<div class="col-md-12 text-left position">
			<button type="button" class="btn btn-success" onclick="window.location='/<?php echo $this->controller;?>/detail';"><i class="fa fa-crosshairs"></i> CREATE REFERRAL CODE AND FILE</button>
	    </div>
	    <div class="col-md-12">
	    	<table id="referralFileTable" class="data-table display" cellspacing="0" width="100%">
	    		<thead>
	    			<tr>
	    				<th width="15px">Id</th>
	    				<th>Code</th>
	    				<th>File Name</th>
	    				<th>Url Share File</th>
	    				<th width="15px">Action</th>
	    			</tr>
	    		</thead>
	    	</table>
	    </div>
    </div>
</div>

