<div class="container">
	<div class="col-md-12 text-center">
		<h1><?php echo $this->translate( "xrace-admin" );?></h1>
	</div>
</div>
<div class="form-box" id="login-box">
	<div class="header"></div>
	<form action="" method="post" class="x-form" name="loginForm" id="loginForm">
		<div class="body bg-gray">
			<?php echo $this->partial( "/partials/_errors.phtml", array( "errors" => $this->error ) ); ?>
			<div class="form-group">
			    <div class="inner-addon right-addon">
                    <i class="glyphicon glyphicon-asterisk"></i>
    				<input type="text" name="username" id="username" class="form-control" placeholder="<?php echo $this->translate( "username" );?>" 
    				value="<?php echo @$this->loginInfo['username'];?>" maxlength="255"/>
                </div>           
			</div>
			<div class="form-group">
			    <div class="inner-addon right-addon">
                    <i class="glyphicon glyphicon-asterisk"></i>
    				<input type="password" name="password" id="password" class="form-control" placeholder="<?php echo $this->translate( "password" );?>" 
    				value="<?php echo @$this->loginInfo['password'];?>" maxlength="255"/>
                </div>           
			</div>
			<div class="form-group">
			    <label><input type="checkbox" name="remember_me" value="1" <?php if( $this->isRemember == 1 ) { ?>  checked="checked"  <?php } ?>/> <?php echo $this->translate( "remember-me" );?></label>
			</div>
		</div>
		<div class="footer text-center">
			<p>
				<button type="submit" class="btn btn-lg btn-block loginButton"><?php echo $this->translate( "login" );?></button>
			</p>
			<p>
				<button onclick="window.location='/<?php echo $this->controller;?>/forgot';" type="button" class="btn btn-link popover-dismiss"><?php echo $this->translate( "forgot-password" );?></button>
			</p>
		</div>
	</form>
</div>