<div class="container-fluid">
	<div class="row">
	    <div class="col-md-12">
			<form class="form-inline x-form" enctype="multipart/form-data" role="form" method="POST" action='/notification' name="notiform">
	      	<div>
				<h3>Account</h3>
				<hr/>
			</div>
			<div class="widget blue">
	      		<div class="widget-title">
				    <h4><i class="fa fa-navicon"></i> DETAIL</h4>
				</div>
	      		<div class="widget-body search-form">
	      			<div class="container-left">
	      	<?php echo $this->partial( "/partials/_errors.phtml", array( "errors" => $this->error ) ); ?>
	        <fieldset>
	    	<div class="form-group col-md-12 padding-left padding-right">
	    		<div class="col-md-6">
	    			<label>Start Time</label>
	    			<input type="text" placeholder="message" class="form-control" name="start" value="<?php echo @$this->gameInfo['time_start']?>">
	    		</div>
	    		<div class="col-md-6">
	    			<label>End Time</label>
	    			<input type="text" placeholder="message" class="form-control" name="end" value="<?php echo @$this->gameInfo['end_time']?>">
	    		</div>
	    		<div class="col-md-6">
	    			<label>Message</label>
	    			<input type="text" placeholder="message" class="form-control" name="message" value="<?php echo @$this->info['message']?>">
	    		</div>
	        </div>
	
	          <div class="form-group col-md-12">
	              <div class="pull-right">
	                <button type="submit" class="btn btn-primary">SUBMIT</button>
	              </div>
	          </div>
	        </fieldset>
			</div>
			</div>
			</div>
	      </form>
	    </div><!-- /.col-lg-12 -->
	</div><!-- /.row -->
</div>