<div class="container-fluid">
	<div class="row">
	    <div class="col-md-12">
		<form class="form-inline x-form" enctype="multipart/form-data" action="" method="post">
			<div>
				<h3>Product</h3>
				<hr/>
			</div>
			<div class="widget blue">
				<div class="widget-title">
					<h4>
						<i class="fa fa-navicon"></i> Upload
					</h4>
				</div>
				<div class="widget-body search-form">
					<div class="container-left">
						<div class="col-md-12">
								<div class="col-md-1">
									<button type="button" id="btnAddImage"
										class="btn btn-success form-control btn-image"
										title="<?php echo $this->translate('add')?>">
										<i class="fa fa-plus"> ADD MORE</i>
									</button>
								</div>
						</div>
						<div class="form-group divParent">
							<div class="col-md-12 divImg_0">
								<div class="col-md-3">
									<input type="file" name="product" class="form-control Image" data-index='0'>
								</div>
								<div class="col-md-1 btnDel_0 hidden">
									<button type="button" class="btn btn-danger btnDelete" data-parent="0">
										<i class="fa fa-trash-o"></i>
									</button>
								</div>
							</div>
						</div>
						<div class="col-md-12">
							<p class="btn-search ">
								<button type="button" class="btn btn-default"
									onclick="window.location = '<?php echo '/'.$this->controller?>';">
									<i class="fa fa-times-circle-o"></i> <?php echo $this->translate("cancel"); ?>
							    </button>
								<button type="submit" id="upload" class="btn btn-primary">
									<i class="fa fa-bullseye"></i> <?php echo $this->translate("submit"); ?>
							    </button>
							</p>
						</div>
						<input type="hidden" id='count-image' value="1" >
					</div>
				</div>
			</div>
		</form>
	</div>
</div>
</div>
