<div class="container-fluid">
	<div class="row">
	    <div class="col-md-12">
			<form class="form-inline x-form"  role="form" method="POST" name="memberDetailForm">
	      	<div class="widget blue">
	      		<div class="widget-title">
				    <h4><i class="fa fa-navicon"></i> DETAIL GROUP JOIN</h4>
				</div>
	      		<div class="widget-body search-form">
	      			<div class="container-left">
					<?php echo $this->partial( "/partials/_errors.phtml", array( "errors" => $this->error ) ); ?>
					<fieldset>
					<div class="form-group col-md-12 padding-right padding-left">
						<div class="col-md-3 padding-left">
							<label><?php echo $this->translate('group-id')?></label>
							<input disabled="disabled" type="text" placeholder="<?php echo $this->translate('group-id')?>" class="form-control" name="id" value="<?php echo @$this->info['group_id']?>">
						</div>
						<div class="col-md-3">
							<label><?php echo $this->translate('user-id')?></label>
							<input disabled="disabled" type="text" placeholder="<?php echo $this->translate('user-id')?>" class="form-control" name="email" value="<?php echo @$this->info['user_id']?>">
						</div>
						<div class="col-md-3">
							<label><?php echo $this->translate('status')?></label>
							<input type="text" disabled="disabled" placeholder="<?php echo $this->translate('status')?>" class="form-control" name="amount" value="<?php echo @$this->info['status']?>">
						</div>
						<div class="col-md-3 padding-right">
							<label><?php echo $this->translate('create-date')?></label>
							<input type="text" disabled="disabled" placeholder="<?php echo $this->translate('create-date')?>" class="form-control" name="productGroupName" value="<?php echo @$this->info['create_date']?>">
						</div>
					</div>
					
					<div class="form-group col-md-12 padding-right">
						<div class="pull-right">
							<button type="button" class="btn btn-default" onclick="window.location = '<?php echo '/'.$this->controller?>';">CANCEL</button>
						</div>
					</div>
					</fieldset>
					</div>
				</div>
			</div>
	      </form>
	    </div><!-- /.col-lg-12 -->
	</div><!-- /.row -->
</div>