<div class="container-fluid">
    <div class="row" style="padding-bottom: 20px">
        <div class="col-md-12">
            <div>
                <h3>Group Join List</h3>
            </div>
            <hr/>
            <!--form class="form-inline search-form search-form-datatable" role="form" method="get" 
            		onsubmit="return false;" action="" id="searchGroupUserForm">
            		<div class="container-left ">
            			<div class="col-md-12 padding-right">
            				<div class="form-group col-md-3">
                				<label for=""><?php echo $this->translate( 'group-name' ); ?></label>
                				<input id="userName" type="text" class="form-control searchItem" placeholder="<?php echo $this->translate( 'group-name' ); ?>"
                           			mapping-column="1" item-type="search" data-type="" data-format=""/>
                			</div>
                			<div class="form-group col-md-3">
                				<label for=""><?php echo $this->translate( 'user-name-leader' ); ?></label>
                				<input id="email" type="text" class="form-control searchItem" placeholder="<?php echo $this->translate( 'user-name-leader' ); ?>"
                           			mapping-column="3" item-type="search" data-type="" data-format=""/>
                			</div>
							<div class="form-group col-md-3">
                				<label for=""><?php echo $this->translate( 'email' ); ?></label>
                				<input id="email" type="text" class="form-control searchItem" placeholder="<?php echo $this->translate( 'email' ); ?>"
                           			mapping-column="5" item-type="search" data-type="" data-format=""/>
                			</div>
							<div class="form-group col-md-3 padding-right">
                				<label for=""><?php echo $this->translate( 'phone' ); ?></label>
                				<input id="email" type="text" class="form-control searchItem" placeholder="<?php echo $this->translate( 'phone' ); ?>"
                           			mapping-column="7" item-type="search" data-type="" data-format=""/>
                			</div>
            			</div>
            			<div class="form-group col-md-12 padding-right">
				            <p class="btn-search ">
				                <button type="button" class="btn btn-primary" id="btnSearch" onclick="PaymentAdmin.site.pages.Common.executeSearchForm('searchGroupUserForm', 'groupUserTable');">
				                    <i class="fa fa-search"></i> <?php echo $this->translate( 'search' ); ?>
				                </button>
				            </p>
				        </div>
            		</div>
            		
            </form-->
    	</div>
    </div>
    <div class="row">
	    <div class="col-md-12">
	    	<table id="groupJoinTable" class="data-table display disable-state-save" cellspacing="0" width="">
	    		<thead>
	    			<tr>
	    				<th width="5%">ID</th>
	    				<th width="10%">Group Id</th>
	    				<th>User Id</th>
	    				<th width="10%">Status</th>
	    				<th width="10%">Create Date</th>
	    				<th width="35px">Action</th>
	    			</tr>
	    		</thead>
	    	</table>
	    </div>
    </div>
</div>
