<div class="container-fluid"> 
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
      <ul class="nav navbar-nav">
        <li> <a href="/index" class="<?php echo ($this->controller == 'index')?'active':''?>"><i class="fa fa-home"></i> HOME</a> </li>
        <li> <a href="/user" class="<?php echo ($this->controller == 'user')?'active':''?>"><i class="fa fa-user"></i> USER LOCAL</a> </li>
        <li> <a href="/product-group" class="<?php echo ($this->controller == 'product-group')?'active':''?>"><i class="fa fa-cubes"></i> PRODUCT-GROUP</a> </li>
        <li> <a href="/product" class="<?php echo ($this->controller == 'product')?'active':''?>"><i class="fa fa-life-ring"></i> PRODUCT</a> </li>
        <li> <a href="/order-detail" class="<?php echo ($this->controller == 'order-detail')?'active':''?>"><i class="fa fa-credit-card"></i> ORDER</a> </li>
        <li> <a href="/member" class="<?php echo ($this->controller == 'member')?'active':''?>"><i class="fa fa-table"></i> USER</a> </li>
		<li> <a href="/group-user" class="<?php echo ($this->controller == 'group-user')?'active':''?>"><i class="fa fa-users"></i> GROUP USER</a> </li>
		<li> <a href="/group-invite" class="<?php echo ($this->controller == 'group-invite')?'active':''?>"><i class="fa fa-table"></i> GROUP INVITE</a> </li>
		<li> <a href="/group-join" class="<?php echo ($this->controller == 'group-join')?'active':''?>"><i class="fa fa-table"></i> GROUP JOIN</a> </li>
      </ul>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><a href="#">Link</a></li> -->
        <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo $this->translate('language')?>: <strong> <?php echo ($this->lang_code == 'es')?'English':'Tiếng Việt'?></strong> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a onclick="PaymentAdmin.site.pages.Common.loadLanguage('es')">English</a></li>
            <li><a onclick="PaymentAdmin.site.pages.Common.loadLanguage('vi')">Tiếng Việt</a></li>
          </ul>
        </li>
        <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo @$this->login_info->full_name?> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          	<li><a href="/user/change-password">Change Password</a></li>
            <li><a href="/login/logout">Logout</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse --> 
  </div>
  
  