<div class="container-fluid">
	<div class="row">
	    <div class="col-md-12">
			<form class="form-inline x-form" enctype="multipart/form-data" role="form" method="POST" name="memberDetailForm">
	      	<div>
				<h3>Order</h3>
				<hr/>
			</div>
			<div class="widget blue">
	      		<div class="widget-title">
				    <h4><i class="fa fa-navicon"></i> DETAIL</h4>
				</div>
	      		<div class="widget-body search-form">
	      			<div class="container-left">
	      <?php echo $this->partial( "/partials/_errors.phtml", array( "errors" => $this->error ) ); ?>
	        <fieldset>
	    	<div class="form-group col-md-12 padding-left padding-right">
	    		<div class="col-md-3">
	    			<label>Id</label>
	    			<input disabled="disabled" type="text" placeholder="<?php echo $this->translate('id')?>" class="form-control" name="id" value="<?php echo @$this->info['order_id']?>">
	    		</div>
	    		<div class="col-md-3">
	    			<label>Order Name</label>
	    			<input disabled="disabled" type="text" placeholder="<?php echo $this->translate('order-name')?>" class="form-control" name="orderName" value="<?php echo @$this->info['order_name']?>">
	    		</div>
	    		<div class="col-md-3">
	    			<label>Product Group Id</label>
	    			<input type="text" disabled="disabled" placeholder="<?php echo $this->translate('proudct-group-id')?>" class="form-control" name="productGroupName" value="<?php echo @$this->info['product_group_id']?>">
	    		</div>
	    		<div class="col-md-3">
	    			<label>Amount</label>
	    			<input type="text" disabled="disabled" placeholder="<?php echo $this->translate('amount')?>" class="form-control" name="amount" value="<?php echo @$this->info['amount']?>">
	    		</div>
	        </div>
	        <div class="form-group col-md-12 padding-left padding-right">
	    		<div class="col-md-3">
	    			<label>Currency</label>
	    			<input type="text" disabled="disabled" data-type="price" placeholder="<?php echo $this->translate('currency')?>" class="form-control" name="currency" value="<?php echo @$this->info['currency']?>">
	    		</div>
	    		<div class="col-md-3">
	    			<label>Payment Amount</label>
	    			<input type="text" disabled="disabled" data-type="price" placeholder="<?php echo $this->translate('payment-amount')?>" class="form-control" name="paymentAmount" value="<?php echo @$this->info['payment_amount']?>">
	    		</div>
	    		<div class="col-md-3">
	    			<label>Payment Fee</label>
	    			<input type="text" disabled="disabled" data-type="price" placeholder="<?php echo $this->translate('payment-fee')?>" class="form-control" name="paymenFee" value="<?php echo @$this->info['payment_fee']?>">
	    		</div>
	    		<div class="col-md-3">
	    			<label>Payment Type Value</label>
	    			<input type="text" disabled="disabled" data-type="price" placeholder="<?php echo $this->translate('payment-type-value')?>" class="form-control" name="paymentTypeValue" value="<?php echo @$this->info['payment_type_value']?>">
	    		</div>
	        </div>
	        <div class="form-group col-md-12 padding-left padding-right">
	    		<div class="col-md-3">
	    			<label>Payment Paypal Id</label>
	    			<input type="text" disabled="disabled" placeholder="<?php echo $this->translate('payment-paypal-id')?>" class="form-control" name="paymentTypeId" value="<?php echo @$this->info['payment_paypal_id']?>">
	    		</div>
	    		<div class="col-md-3">
	    			<label>Payment Cash Code</label>
	    			<input type="text" disabled="disabled" placeholder="<?php echo $this->translate('payment-cash-code')?>" class="form-control" name="paymentCashCode" value="<?php echo @$this->info['payment_cash_code']?>">
	    		</div>
	    		<div class="col-md-3">
	    			<label>Payment Status</label>
	    			<input type="text" disabled="disabled" placeholder="<?php echo $this->translate('payment_status')?>" class="form-control" name="paymentStatus" value="<?php echo @$this->info['payment_status']?>">
	    		</div>
	    		<div class="col-md-3">
	    			<label>Created At</label>
	    			<input type="text" disabled="disabled" placeholder="<?php echo $this->translate('created-at')?>" class="form-control" name="createAt" value="<?php echo @$this->info['created_at']?>">
	    		</div>
	        </div>
	        <div class="form-group col-md-12 padding-left padding-right">
	    		<div class="col-md-12">
	    			<label>Email</label>
	    			<input type="text" disabled="disabled" placeholder="<?php echo $this->translate('email')?>" class="form-control" name="email" value="<?php echo @$this->info['email']?>">
	    		</div>
	        </div>
	        <div class="form-group col-md-12">
	              <div class="pull-right">
	                <button type="button" class="btn btn-default" onclick="window.location = '<?php echo '/'.$this->controller?>';">CANCEL</button>
	              </div>
	        </div>
	        </fieldset>
			</div>
			</div>
			</div>
	      </form>
	    </div><!-- /.col-lg-12 -->
	</div><!-- /.row -->
</div>