
<div class="container-fluid">
	<div class="row">
	    <div class="col-md-12">
			<form class="form-inline x-form" enctype="multipart/form-data" role="form" method="POST" name="memberDetailForm">
	      	<div>
				<h3>Question</h3>
				<hr/>
			</div>
			<div class="widget blue">
	      		<div class="widget-title">
				    <h4><i class="fa fa-navicon"></i> DETAIL</h4>
				</div>
	      		<div class="widget-body search-form">
	      			<div class="container-left">
			  <?php echo $this->partial( "/partials/_errors.phtml", array( "errors" => $this->error ) ); ?>
				<fieldset>
				<div class="form-group col-md-12 padding-left padding-right">
					<div class="col-md-4 padding-left">
						<label>Answer</label>
						<input type="text"  placeholder="Answer" class="form-control" id="answer" name="answer" value="<?php echo @$this->info['answer']?>">
					</div>
					<div class="col-md-2">
						<label>Name</label>
						<input type="text"  placeholder="Name" class="form-control" id="name" name="name" value="<?php echo @$this->info['name']?>">
					</div>
					<div class="col-md-2">
						<label>Type</label>
						<select class="form-control" id="type" name="type">
							<?php echo $this->partial( "/partials/_question-type.phtml", array( "list" => Commons::typeQuestion(), 'value' => @$this->info['type'] ) ); ?>
						</select>
					</div>
					<div class="col-md-2">
						<label>Stage</label>
						<select class="form-control" id="" name="id_stage">
							<?php echo $this->partial( "/partials/_stage.phtml", array( "list" => @$this->stageList, 'value' => @$this->info['id_stage'] ) ); ?>
						</select>
					</div>
					
					<div class="col-md-2 padding-right">
						<label>Max Time</label>
						<input type="text"  placeholder="Max Time" class="form-control" id="max_time" name="max_time" value="<?php echo @$this->info['max_time']?>">
					</div>
				</div>
				<div class="form-group col-md-12 padding-left padding-right">
					<label>Content</label>
					<textarea name="content" rows="10" id="content" cols="80"><?php echo @$this->info['content']?></textarea>
					<script type="text/javascript">CKEDITOR.replace( 'content' );</script>
				</div>
				<div class="form-group col-md-12 padding-right">
					<div class="pull-right">
						<button type="button" class="btn btn-default" onclick="window.location = '<?php echo '/'.$this->controller?>';">CANCEL</button>
						<button type="submit" id="submit" class="btn btn-primary">SUBMIT</button>
					</div>
				</div>
				</fieldset>
						</div>
					</div>
				</div>
			</form>
	    </div><!-- /.col-lg-12 -->
	</div><!-- /.row -->
</div>