<div class="modal-dialog">
	<div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">
				<span aria-hidden="true">&times;</span><span class="sr-only">Close</span>
			</button>
		</div>
		<div class="modal-body" style="text-align: center;">
			<img src="<?php echo BASE_PATH.'/upload/'.$this->logo?>">
		</div>
		<div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">CLOSE</button> 
		</div>
	</div>
</div>
