<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink(); ?>
		 <?php echo $this->headScript(); ?>
    </head>
    <body>
        <div class="wrapper">
            <img class="logo" src="/resources/images/logo.png" />
            <div class="file">
                <span><i>File Not Found</i></span>
            </div>
        </div>
    </body>
</html>