<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        
		<?php echo $this->headMeta(); ?>
		<?php echo $this->headTitle(); ?>
		<?php echo $this->headLink(); ?>
		
    </head>
    <body>
        <div class="wrapper">
            <img class="logo" src="/resources/images/logo.png" />
            <div class="file">
                <span><?php echo @$this->codeInfo['file_name']?></span>
            </div>
            <a class="button" download="<?php echo @$this->codeInfo['file_name']?>" href="<?php echo $this->host.@$this->codeInfo['physical_name']?>">DOWNLOAD NOW!</a>
        </div>
    </body>
</html>
 <?php echo $this->headScript(); ?>