<div class="container-fluid">
    <div class="row" style="padding-bottom: 20px">
        <div class="col-md-12">
            <div>
                <h3><?php echo $this->translate( "group-invite-list" ); ?></h3>
            </div>
            <hr/>
    	</div>
    </div>
    <div class="row">
	    <div class="col-md-12">
	    	<table id="groupInviteTable" class="data-table display disable-state-save" cellspacing="0" width="">
	    		<thead>
	    			<tr>
	    				<th width="5%">ID</th>
	    				<th width="10%">Group Invite</th>
	    				<th>User Invite</th>
	    				<th width="10%">Status</th>
	    				<th width="10%">Create Date</th>
	    				<th width="35px">Action</th>
	    			</tr>
	    		</thead>
	    	</table>
	    </div>
    </div>
</div>
