<div class="container-fluid"> 
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
      <ul class="nav navbar-nav">
        <li> <a href="/user" class="active"><i class="fa fa-qrcode"></i>USER</a> </li>
        <li> <a href="/account"><i class="fa fa-gift"></i>ACCOUNT</a> </li>
        <li> <a href="#"><i class="fa fa-send"></i>NOTIFICATION</a> </li>
        <li> <a href="#"><i class="fa fa-tint"></i>CONFIGURATION</a> </li>
        <li> <a href="#"><i class="fa fa-tint"></i>PRODUCT</a> </li>
      </ul>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><a href="#">Link</a></li> -->
        <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown">Language: <strong>English</strong> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="profiles.html">English</a></li>
            <li><a href="profiles.html">Tiếng Việt</a></li>
          </ul>
        </li>
        <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?php echo @$this->login_info->full_name?> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
          	<li><a href="/user/change-password">Change Password</a></li>
            <li><a href="/login/logout">Logout</a></li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse --> 
  </div>
  